spring:
  application:
    name: itcast-haoke-manage-dubbo-server-ad

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.111.132:3306/haoke?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=fals
    username: root
    password: root

dubbo:
  scan:
    basePackages: cn.itcast.haoke.dubbo.server.api
  application:
    name: dubbo-provider-ad
  protocol:
    port: 21880
    name: dubbo
  registry:
    client: zkclient
    address: zookeeper://192.168.111.132:2181